apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: green-datacenter-selector
  labels:
    app: green-datacenter-selector
    app.kubernetes.io/name: green-datacenter-selector
spec:
  lookupPolicy:
    local: false

# Made with Bob
